export const BeTheHouse = () => {
    return (
        <section className="landing-page__be-the-house">
            <div className="content">
              <h2 className="heading-lg">Be The House</h2>
              <p>
                Provide liquidity to Divvy and share the profits generated by betting activity. As a user, you can deposit USDT into the House pool in return for House tokens that represent your share of the pool as well as its profits.
              </p>
            </div>
        </section>
    );
};
  